Repository pinax-network/pinax-token-api, pull requests merged in 2025-03, with the labels that each got.

#4 Refactor OpenAPI repo & SQL API
  .env.example
  CONTRIBUTING.md
  LICENSE
  README.md
  favicon.ico
  index.ts
  kubb.config.ts
  package.json
  src/clickhouse/makeQuery.ts
  src/config.ts
  src/handleQuery.ts
  src/routes/health.ts
  src/routes/index.ts
  src/routes/metrics.ts
  src/routes/token/balances/evm/index.ts
  src/routes/token/balances/index.ts
  src/routes/token/holders/evm/index.ts
  src/routes/token/holders/index.ts
  src/routes/token/index.ts
  src/routes/token/transfers/evm/index.ts
  src/routes/token/transfers/index.ts
  src/routes/version.ts
  src/types/README.md
  src/types/api.ts
  src/types/zod.gen.ts
  src/types/zod.ts
  src/typespec/README.md
  src/typespec/main.tsp
  src/typespec/models.tsp
  src/typespec/openapi3.tsp
  src/usage.ts
  src/utils.ts
  static/@typespec/openapi3/openapi.json
  stoplight/index.html
  token_api_architecture_diagram.png
  tspconfig.yaml
Labels: documentation

#6 Replace Valibot validator with Zod for API routes
  .gitignore
  bun.lock
  package.json
  src/routes/token/balances/evm.ts
  src/routes/token/holders/evm.ts
  src/routes/token/transfers/evm.ts
  src/types/valibot.spec.ts
  src/types/valibot.ts
  src/types/zod.spec.ts
  src/types/zod.ts
Labels: ops

#15 add `makeUsageQueryJson` method
  src/handleQuery.ts
  src/routes/token/balances/evm.ts
  src/routes/token/holders/evm.ts
  src/routes/token/tokens/evm.ts
  src/routes/token/transfers/evm.ts
Labels: bug

#17 Bump SS package to `1.9.0`, add `arbitrum-one`
  src/config.ts
  src/routes/token/index.ts
Labels: ops

#21 Update Docs
  .github/release-drafter.yml
  .github/workflows/bun-build.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  bun.lock
  config.example.yaml
  index.ts
  package.json
  public/index.html
  src/config.ts
  src/mcp/index.ts
  src/routes/health.ts
  src/routes/metrics.ts
  src/routes/networks.ts
  src/routes/version.ts
  src/types/zod.ts
Labels: documentation, ops

#23 Reduce SHOW TABLES & SHOW DATABASE
  src/mcp/tools.ts
Labels: bug

#24 update app version build
  .github/workflows/ghcr.yml
  Dockerfile
  README.md
  bun.lock
  index.ts
  package.json
  src/config.ts
  src/logger.ts
  src/mcp/index.ts
  src/routes/version.ts
  src/sql/index.ts
Labels: documentation, ops
